### PR TITLE
add solutions for 002

### PR DESCRIPTION
**Pull request by victoriacheng15**
## Description 

add solutions for valid palindrome problem

## Fixes Issue

N/A

## Screenshots - if applicatable
N/A

## Checklist:

- [x] Does it contain "Author: [your name]"?
- [x] Does it have pseudocode?
- [x] Does it include testing, e.g. Jest?

### CODE REVIEW

**Review by abdulqshabbir — APPROVED** [review]
Solution looks good overall!
On line 86 I think we should use camelCase since `LowerCase` is not a constructor function, class, etc.

Let me know if you have any feedback for my code!

**Comment by victoriacheng15** [comment]
> Solution looks good overall! On line 86 I think we should use camelCase since `LowerCase` is not a constructor function, class, etc.
> 
> Let me know if you have any feedback for my code!

Oh, I see, not sure how I typed `LowerCase` instead. I am changing `lowerCase` shortly.

**Comment by victoriacheng15** [comment]
> Let me know if you have any feedback for my code!

If I understand correct, you are comparing the start of the string with the end of the string? 

level
---->
level
<----

This is an interesting solution.

**Comment by abdulqshabbir** [comment]
> If I understand correct, you are comparing the start of the string with the end of the string?

Yep, I'm comparing the start and end character and then repeatedly doing that on each of the substrings after we remove the start and end character.

"racecar"
-> True && "aceca"
-> True && True && "cec"
-> True && True && True && "e"

Each time the first and last characters are the same `str[0] === str[end]` will return true
The first and last characters are removed and the remaining substring is passed to another function call.
Until it reaches "e" will return true since it is a base case.

If any of the function calls return false, the && operation will return false overall.

**Pull request merged**
